### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-select-list'

### ISSUE THREAD

**Issue by eeboaz** [mark-hahn/shell-it#7]
1. Install 'shell-it' via Preferences > Install

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: [shell-it](https://github.com/damnedscholar/shell-it) package 0.4.0

### Stack Trace

Uncaught Error: Cannot find module 'atom-select-list'

```
At module.js:472

Error: Cannot find module 'atom-select-list'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/shell-it/lib/shell-it.js:5:20)
    at /packages/shell-it/lib/shell-it.js:291:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:267:16)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:794:40)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:439:22)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:431:18)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:728:22
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:811:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:659:33)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:498:32
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at bufferStream (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:280:15)
    at Socket.stream.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
     -2:46.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
shell-it 0.4.0 
```

**Comment by frommeyerc** [comment]
Looks like it is missing in `package.json`. I manually run an `npm install --save atom-select-list` in the plugin directory and `apm link`ed it.That made it work.

**Comment by dklann** [comment]
Seeing this error on Arch Linux as well. Manually installing `atom-select-list` (thanks @frommeyerc) solved this for me. Thanks!

**Comment by jest** [comment]
I created PR for this issue; in the meantime, if you don't want to touch the command line, just uninstall shell-it and install package `jest/shell-it` instead.

![image](https://user-images.githubusercontent.com/161816/42445322-121b5060-8373-11e8-8ea9-08177a0dd796.png)
